### ISSUE TITLE
Some new functions and example scripts

### ISSUE THREAD

**Issue by MrSmits** [liampkemp/Enabler#1]
I've added some new functions and example scripts, can I contribute?

**Comment by liampkemp** [comment]
Absolutely. I'm still getting the hang of GitHub, so if there is anything that I need to do to let you contribute, let me know

**Comment by MrSmits** [comment]
I can off course create pull request, like I just did. But it would make it a bit easier for me if you can add me as a collaborator on the repo settings page :)
